name: My First Workflow

on:
  workflow_dispatch: # 允許在網頁上手動按按鈕觸發
  push:
    branches: [ "main" ] # 當 main 分支有異動時觸發

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, GitHub Actions is working!"
